import { z } from 'zod';

/**
 * A primary key generated by the database layer (cuid2).
 *
 * Kept permissive on the exact alphabet but strict on shape: identifiers arrive
 * from URLs and request bodies, so the schema exists to reject obviously hostile
 * input early, not to authenticate it. Ownership is a separate, server-side
 * check — never infer access from the fact that an id parsed.
 */
export const entityIdSchema = z
  .string()
  .trim()
  .min(8, { message: 'must be at least 8 characters' })
  .max(64, { message: 'must be at most 64 characters' })
  .regex(/^[A-Za-z0-9_-]+$/, {
    message: 'must contain only letters, digits, hyphen or underscore',
  });

/**
 * An email address, normalised to lower case.
 *
 * Normalisation happens at the boundary so that the unique constraint on
 * `User.email` cannot be bypassed by changing capitalisation.
 */
export const emailSchema = z
  .email({ message: 'must be a valid email address' })
  .max(320, { message: 'must be at most 320 characters' })
  .transform((value) => value.trim().toLowerCase());

/**
 * True when `value` contains an ASCII control character.
 *
 * Written as a code-point scan rather than a regular expression so the source
 * file itself stays free of literal control characters.
 */
const hasControlCharacters = (value: string): boolean => {
  for (const character of value) {
    const code = character.codePointAt(0) ?? 0;
    if (code < 0x20 || code === 0x7f) {
      return true;
    }
  }
  return false;
};

/**
 * An identifier issued by an external provider (a Google calendar or event id).
 *
 * Provider ids are opaque and outside our control, so the schema only bounds
 * their length and forbids control characters, which would otherwise reach logs
 * and terminals verbatim.
 */
export const externalIdSchema = z
  .string()
  .trim()
  .min(1, { message: 'must not be empty' })
  .max(512, { message: 'must be at most 512 characters' })
  .refine((value) => !hasControlCharacters(value), {
    message: 'must not contain control characters',
  });
